apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: layer1
spec:
  hosts:
  - layer1
  http:
  - match:
    - uri:
        exact: /
      method:
        exact: POST
    route:
    - destination:
        host: layer1
        port:
          number: 8080
        subset: v1