apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    pipeline.openshift.io/type: kubernetes
  name: get-and-push-image
spec:
  params:
  - name: STORAGE_DRIVER            # Used for the build step to tell Buildah how to store images
    type: string
  - name: quay-io-account                   # Quay.io account name
    type: string
  - name: quay-io-repository                # Quay.io repository name
    type: string
  - name: quay-io-image-tag-name            # Quay.io repository image tag
    type: string
    default: "latest"  
  - name: image-stream-location
    type: string    
##------------------------------------------------------------------
# Push the new runtime image to quay.io
##------------------------------------------------------------------
  tasks:
  - name: push-image-to-quay
    params:
      - name: quay-io-account
        value: $(params.quay-io-account)
      - name: quay-io-repository
        value: $(params.quay-io-repository)
      - name: quay-io-image-tag-name
        value: $(params.quay-io-image-tag-name)
      - name: image-stream-location
        value: $(params.image-stream-location)
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
    taskRef:
      kind: Task
      name: push-image-to-quay
    workspaces:
    - name: files
      workspace: files
##------------------------------------------------------------------
# Workspace definition.
##------------------------------------------------------------------         
  workspaces:
  - name: files  